//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACTIVOSEntities16 : DbContext
    {
        public ACTIVOSEntities16()
            : base("name=ACTIVOSEntities16")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbActivos> tbActivos { get; set; }
        public virtual DbSet<tbVidaUtil> tbVidaUtil { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
    
        public virtual ObjectResult<UDP_IniciarSesion_Result> UDP_IniciarSesion(string usua_Usuario, string usua_Contra)
        {
            var usua_UsuarioParameter = usua_Usuario != null ?
                new ObjectParameter("usua_Usuario", usua_Usuario) :
                new ObjectParameter("usua_Usuario", typeof(string));
    
            var usua_ContraParameter = usua_Contra != null ?
                new ObjectParameter("usua_Contra", usua_Contra) :
                new ObjectParameter("usua_Contra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IniciarSesion_Result>("UDP_IniciarSesion", usua_UsuarioParameter, usua_ContraParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbusuarios_CambiarPassword(string usua_Usuario, string usua_Contra)
        {
            var usua_UsuarioParameter = usua_Usuario != null ?
                new ObjectParameter("usua_Usuario", usua_Usuario) :
                new ObjectParameter("usua_Usuario", typeof(string));
    
            var usua_ContraParameter = usua_Contra != null ?
                new ObjectParameter("usua_Contra", usua_Contra) :
                new ObjectParameter("usua_Contra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbusuarios_CambiarPassword", usua_UsuarioParameter, usua_ContraParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbUsuarios_DeshabilitarUsuarios(Nullable<int> usua_Id)
        {
            var usua_IdParameter = usua_Id.HasValue ?
                new ObjectParameter("usua_Id", usua_Id) :
                new ObjectParameter("usua_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbUsuarios_DeshabilitarUsuarios", usua_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbusuarios_EditarUsuario(Nullable<int> usua_Id, string usua_UsuarioNombre, string usua_UsuarioApellido, Nullable<int> usua_UsuarioModificacion)
        {
            var usua_IdParameter = usua_Id.HasValue ?
                new ObjectParameter("usua_Id", usua_Id) :
                new ObjectParameter("usua_Id", typeof(int));
    
            var usua_UsuarioNombreParameter = usua_UsuarioNombre != null ?
                new ObjectParameter("usua_UsuarioNombre", usua_UsuarioNombre) :
                new ObjectParameter("usua_UsuarioNombre", typeof(string));
    
            var usua_UsuarioApellidoParameter = usua_UsuarioApellido != null ?
                new ObjectParameter("usua_UsuarioApellido", usua_UsuarioApellido) :
                new ObjectParameter("usua_UsuarioApellido", typeof(string));
    
            var usua_UsuarioModificacionParameter = usua_UsuarioModificacion.HasValue ?
                new ObjectParameter("usua_UsuarioModificacion", usua_UsuarioModificacion) :
                new ObjectParameter("usua_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbusuarios_EditarUsuario", usua_IdParameter, usua_UsuarioNombreParameter, usua_UsuarioApellidoParameter, usua_UsuarioModificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbUsuarios_HabilitarUsuarios(Nullable<int> usua_Id)
        {
            var usua_IdParameter = usua_Id.HasValue ?
                new ObjectParameter("usua_Id", usua_Id) :
                new ObjectParameter("usua_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbUsuarios_HabilitarUsuarios", usua_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbusuarios_InsertarUsuario(string usua_UsuarioNombre, string usua_UsuarioApellido, string usua_Usuario, string usua_Contra, Nullable<int> usua_UsuarioCreacion)
        {
            var usua_UsuarioNombreParameter = usua_UsuarioNombre != null ?
                new ObjectParameter("usua_UsuarioNombre", usua_UsuarioNombre) :
                new ObjectParameter("usua_UsuarioNombre", typeof(string));
    
            var usua_UsuarioApellidoParameter = usua_UsuarioApellido != null ?
                new ObjectParameter("usua_UsuarioApellido", usua_UsuarioApellido) :
                new ObjectParameter("usua_UsuarioApellido", typeof(string));
    
            var usua_UsuarioParameter = usua_Usuario != null ?
                new ObjectParameter("usua_Usuario", usua_Usuario) :
                new ObjectParameter("usua_Usuario", typeof(string));
    
            var usua_ContraParameter = usua_Contra != null ?
                new ObjectParameter("usua_Contra", usua_Contra) :
                new ObjectParameter("usua_Contra", typeof(string));
    
            var usua_UsuarioCreacionParameter = usua_UsuarioCreacion.HasValue ?
                new ObjectParameter("usua_UsuarioCreacion", usua_UsuarioCreacion) :
                new ObjectParameter("usua_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbusuarios_InsertarUsuario", usua_UsuarioNombreParameter, usua_UsuarioApellidoParameter, usua_UsuarioParameter, usua_ContraParameter, usua_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbUsuarios_ListarUsuarios_Result> UDP_tbUsuarios_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbUsuarios_ListarUsuarios_Result>("UDP_tbUsuarios_ListarUsuarios");
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbUsuarios_VerificarUsuarios(string usua_Usuario)
        {
            var usua_UsuarioParameter = usua_Usuario != null ?
                new ObjectParameter("usua_Usuario", usua_Usuario) :
                new ObjectParameter("usua_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbUsuarios_VerificarUsuarios", usua_UsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tb_Activos_DarBajaActivo(Nullable<int> acvo_Id)
        {
            var acvo_IdParameter = acvo_Id.HasValue ?
                new ObjectParameter("acvo_Id", acvo_Id) :
                new ObjectParameter("acvo_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tb_Activos_DarBajaActivo", acvo_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbActivos_DarDeBajaActivo(Nullable<int> acvo_Id)
        {
            var acvo_IdParameter = acvo_Id.HasValue ?
                new ObjectParameter("acvo_Id", acvo_Id) :
                new ObjectParameter("acvo_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbActivos_DarDeBajaActivo", acvo_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbActivos_EditarActivos(Nullable<int> acvo_Id, string acvo_Nombre, string acvo_NumeroSerie, Nullable<int> viut_Id, Nullable<int> clie_Id, string acvo_Ubicacion, Nullable<System.DateTime> acvo_FechaAdquisicion, Nullable<decimal> acvo_CostoOriginal, Nullable<int> usua_Modificacion)
        {
            var acvo_IdParameter = acvo_Id.HasValue ?
                new ObjectParameter("acvo_Id", acvo_Id) :
                new ObjectParameter("acvo_Id", typeof(int));
    
            var acvo_NombreParameter = acvo_Nombre != null ?
                new ObjectParameter("acvo_Nombre", acvo_Nombre) :
                new ObjectParameter("acvo_Nombre", typeof(string));
    
            var acvo_NumeroSerieParameter = acvo_NumeroSerie != null ?
                new ObjectParameter("acvo_NumeroSerie", acvo_NumeroSerie) :
                new ObjectParameter("acvo_NumeroSerie", typeof(string));
    
            var viut_IdParameter = viut_Id.HasValue ?
                new ObjectParameter("viut_Id", viut_Id) :
                new ObjectParameter("viut_Id", typeof(int));
    
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            var acvo_UbicacionParameter = acvo_Ubicacion != null ?
                new ObjectParameter("acvo_Ubicacion", acvo_Ubicacion) :
                new ObjectParameter("acvo_Ubicacion", typeof(string));
    
            var acvo_FechaAdquisicionParameter = acvo_FechaAdquisicion.HasValue ?
                new ObjectParameter("acvo_FechaAdquisicion", acvo_FechaAdquisicion) :
                new ObjectParameter("acvo_FechaAdquisicion", typeof(System.DateTime));
    
            var acvo_CostoOriginalParameter = acvo_CostoOriginal.HasValue ?
                new ObjectParameter("acvo_CostoOriginal", acvo_CostoOriginal) :
                new ObjectParameter("acvo_CostoOriginal", typeof(decimal));
    
            var usua_ModificacionParameter = usua_Modificacion.HasValue ?
                new ObjectParameter("usua_Modificacion", usua_Modificacion) :
                new ObjectParameter("usua_Modificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbActivos_EditarActivos", acvo_IdParameter, acvo_NombreParameter, acvo_NumeroSerieParameter, viut_IdParameter, clie_IdParameter, acvo_UbicacionParameter, acvo_FechaAdquisicionParameter, acvo_CostoOriginalParameter, usua_ModificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbActivos_InsertarActivos(string acvo_Nombre, string acvo_NumeroSerie, Nullable<int> viut_Id, Nullable<int> clie_Id, string acvo_Ubicacion, Nullable<System.DateTime> acvo_FechaAdquisicion, Nullable<decimal> acvo_CostoOriginal, Nullable<int> usua_UsuarioCreacion)
        {
            var acvo_NombreParameter = acvo_Nombre != null ?
                new ObjectParameter("acvo_Nombre", acvo_Nombre) :
                new ObjectParameter("acvo_Nombre", typeof(string));
    
            var acvo_NumeroSerieParameter = acvo_NumeroSerie != null ?
                new ObjectParameter("acvo_NumeroSerie", acvo_NumeroSerie) :
                new ObjectParameter("acvo_NumeroSerie", typeof(string));
    
            var viut_IdParameter = viut_Id.HasValue ?
                new ObjectParameter("viut_Id", viut_Id) :
                new ObjectParameter("viut_Id", typeof(int));
    
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            var acvo_UbicacionParameter = acvo_Ubicacion != null ?
                new ObjectParameter("acvo_Ubicacion", acvo_Ubicacion) :
                new ObjectParameter("acvo_Ubicacion", typeof(string));
    
            var acvo_FechaAdquisicionParameter = acvo_FechaAdquisicion.HasValue ?
                new ObjectParameter("acvo_FechaAdquisicion", acvo_FechaAdquisicion) :
                new ObjectParameter("acvo_FechaAdquisicion", typeof(System.DateTime));
    
            var acvo_CostoOriginalParameter = acvo_CostoOriginal.HasValue ?
                new ObjectParameter("acvo_CostoOriginal", acvo_CostoOriginal) :
                new ObjectParameter("acvo_CostoOriginal", typeof(decimal));
    
            var usua_UsuarioCreacionParameter = usua_UsuarioCreacion.HasValue ?
                new ObjectParameter("usua_UsuarioCreacion", usua_UsuarioCreacion) :
                new ObjectParameter("usua_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbActivos_InsertarActivos", acvo_NombreParameter, acvo_NumeroSerieParameter, viut_IdParameter, clie_IdParameter, acvo_UbicacionParameter, acvo_FechaAdquisicionParameter, acvo_CostoOriginalParameter, usua_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbActivos_ListarActivos_Result> UDP_tbActivos_ListarActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbActivos_ListarActivos_Result>("UDP_tbActivos_ListarActivos");
        }
    
        public virtual ObjectResult<UDP_tbActivos_ReporteFechas_Result> UDP_tbActivos_ReporteFechas(Nullable<int> clie_Id, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbActivos_ReporteFechas_Result>("UDP_tbActivos_ReporteFechas", clie_IdParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbActivos_VerificarActivosCliente(Nullable<int> clie_Id)
        {
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbActivos_VerificarActivosCliente", clie_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbActivos_VerificarActivosNoDadosBajaCliente(Nullable<int> clie_Id)
        {
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbActivos_VerificarActivosNoDadosBajaCliente", clie_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbActivos_VerificarActivosTotalesCliente(Nullable<int> clie_Id)
        {
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbActivos_VerificarActivosTotalesCliente", clie_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbClientes_CantidadDeClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbClientes_CantidadDeClientes");
        }
    
        public virtual ObjectResult<UDP_tbClientes_ClienteConActivosBajados_Result> UDP_tbClientes_ClienteConActivosBajados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbClientes_ClienteConActivosBajados_Result>("UDP_tbClientes_ClienteConActivosBajados");
        }
    
        public virtual ObjectResult<UDP_tbClientes_ClienteConActivosNoBajados_Result> UDP_tbClientes_ClienteConActivosNoBajados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbClientes_ClienteConActivosNoBajados_Result>("UDP_tbClientes_ClienteConActivosNoBajados");
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbVidaUtil_Editar(Nullable<int> viut_Id, string viut_Objeto, string viut_Descripcion, Nullable<int> viut_VidaUtil, Nullable<int> usuarioModificacion)
        {
            var viut_IdParameter = viut_Id.HasValue ?
                new ObjectParameter("viut_Id", viut_Id) :
                new ObjectParameter("viut_Id", typeof(int));
    
            var viut_ObjetoParameter = viut_Objeto != null ?
                new ObjectParameter("viut_Objeto", viut_Objeto) :
                new ObjectParameter("viut_Objeto", typeof(string));
    
            var viut_DescripcionParameter = viut_Descripcion != null ?
                new ObjectParameter("viut_Descripcion", viut_Descripcion) :
                new ObjectParameter("viut_Descripcion", typeof(string));
    
            var viut_VidaUtilParameter = viut_VidaUtil.HasValue ?
                new ObjectParameter("viut_VidaUtil", viut_VidaUtil) :
                new ObjectParameter("viut_VidaUtil", typeof(int));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbVidaUtil_Editar", viut_IdParameter, viut_ObjetoParameter, viut_DescripcionParameter, viut_VidaUtilParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbVidaUtil_Insertar(string viut_Objeto, string viut_Descripcion, Nullable<int> viut_VidaUtil, Nullable<int> usuarioCreacion)
        {
            var viut_ObjetoParameter = viut_Objeto != null ?
                new ObjectParameter("viut_Objeto", viut_Objeto) :
                new ObjectParameter("viut_Objeto", typeof(string));
    
            var viut_DescripcionParameter = viut_Descripcion != null ?
                new ObjectParameter("viut_Descripcion", viut_Descripcion) :
                new ObjectParameter("viut_Descripcion", typeof(string));
    
            var viut_VidaUtilParameter = viut_VidaUtil.HasValue ?
                new ObjectParameter("viut_VidaUtil", viut_VidaUtil) :
                new ObjectParameter("viut_VidaUtil", typeof(int));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbVidaUtil_Insertar", viut_ObjetoParameter, viut_DescripcionParameter, viut_VidaUtilParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbVidaUtil_ListarVidaUtil_Result> UDP_tbVidaUtil_ListarVidaUtil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbVidaUtil_ListarVidaUtil_Result>("UDP_tbVidaUtil_ListarVidaUtil");
        }
    
        public virtual ObjectResult<UDP_tbVidaUtil_VidaUtilMasUsadas_Result> UDP_tbVidaUtil_VidaUtilMasUsadas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbVidaUtil_VidaUtilMasUsadas_Result>("UDP_tbVidaUtil_VidaUtilMasUsadas");
        }
    
        public virtual ObjectResult<GenerarReportePorCliente_Result> GenerarReportePorCliente(Nullable<int> clie_Id, Nullable<bool> acvo_Estado)
        {
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            var acvo_EstadoParameter = acvo_Estado.HasValue ?
                new ObjectParameter("acvo_Estado", acvo_Estado) :
                new ObjectParameter("acvo_Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerarReportePorCliente_Result>("GenerarReportePorCliente", clie_IdParameter, acvo_EstadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbClientes_EditarClientes(Nullable<int> clie_Id, string clie_CodigoCompania, string clie_NombreCliente, string clie_RTNCliente, string clie_Lugar, string clie_Responsale, string clie_Telefono, Nullable<int> usua_Modificacion)
        {
            var clie_IdParameter = clie_Id.HasValue ?
                new ObjectParameter("clie_Id", clie_Id) :
                new ObjectParameter("clie_Id", typeof(int));
    
            var clie_CodigoCompaniaParameter = clie_CodigoCompania != null ?
                new ObjectParameter("clie_CodigoCompania", clie_CodigoCompania) :
                new ObjectParameter("clie_CodigoCompania", typeof(string));
    
            var clie_NombreClienteParameter = clie_NombreCliente != null ?
                new ObjectParameter("clie_NombreCliente", clie_NombreCliente) :
                new ObjectParameter("clie_NombreCliente", typeof(string));
    
            var clie_RTNClienteParameter = clie_RTNCliente != null ?
                new ObjectParameter("clie_RTNCliente", clie_RTNCliente) :
                new ObjectParameter("clie_RTNCliente", typeof(string));
    
            var clie_LugarParameter = clie_Lugar != null ?
                new ObjectParameter("clie_Lugar", clie_Lugar) :
                new ObjectParameter("clie_Lugar", typeof(string));
    
            var clie_ResponsaleParameter = clie_Responsale != null ?
                new ObjectParameter("clie_Responsale", clie_Responsale) :
                new ObjectParameter("clie_Responsale", typeof(string));
    
            var clie_TelefonoParameter = clie_Telefono != null ?
                new ObjectParameter("clie_Telefono", clie_Telefono) :
                new ObjectParameter("clie_Telefono", typeof(string));
    
            var usua_ModificacionParameter = usua_Modificacion.HasValue ?
                new ObjectParameter("usua_Modificacion", usua_Modificacion) :
                new ObjectParameter("usua_Modificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbClientes_EditarClientes", clie_IdParameter, clie_CodigoCompaniaParameter, clie_NombreClienteParameter, clie_RTNClienteParameter, clie_LugarParameter, clie_ResponsaleParameter, clie_TelefonoParameter, usua_ModificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbClientes_InsertarClientes(string clie_CodigoCompania, string clie_NombreCliente, string clie_RTNCliente, string clie_Lugar, string clie_Responsale, string clie_Telefono, Nullable<int> usua_UsuarioCreacion)
        {
            var clie_CodigoCompaniaParameter = clie_CodigoCompania != null ?
                new ObjectParameter("clie_CodigoCompania", clie_CodigoCompania) :
                new ObjectParameter("clie_CodigoCompania", typeof(string));
    
            var clie_NombreClienteParameter = clie_NombreCliente != null ?
                new ObjectParameter("clie_NombreCliente", clie_NombreCliente) :
                new ObjectParameter("clie_NombreCliente", typeof(string));
    
            var clie_RTNClienteParameter = clie_RTNCliente != null ?
                new ObjectParameter("clie_RTNCliente", clie_RTNCliente) :
                new ObjectParameter("clie_RTNCliente", typeof(string));
    
            var clie_LugarParameter = clie_Lugar != null ?
                new ObjectParameter("clie_Lugar", clie_Lugar) :
                new ObjectParameter("clie_Lugar", typeof(string));
    
            var clie_ResponsaleParameter = clie_Responsale != null ?
                new ObjectParameter("clie_Responsale", clie_Responsale) :
                new ObjectParameter("clie_Responsale", typeof(string));
    
            var clie_TelefonoParameter = clie_Telefono != null ?
                new ObjectParameter("clie_Telefono", clie_Telefono) :
                new ObjectParameter("clie_Telefono", typeof(string));
    
            var usua_UsuarioCreacionParameter = usua_UsuarioCreacion.HasValue ?
                new ObjectParameter("usua_UsuarioCreacion", usua_UsuarioCreacion) :
                new ObjectParameter("usua_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbClientes_InsertarClientes", clie_CodigoCompaniaParameter, clie_NombreClienteParameter, clie_RTNClienteParameter, clie_LugarParameter, clie_ResponsaleParameter, clie_TelefonoParameter, usua_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbClientes_ListarClientes_Result> UDP_tbClientes_ListarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbClientes_ListarClientes_Result>("UDP_tbClientes_ListarClientes");
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_tbClientes_ValidarRTN(string clie_RTNCliente)
        {
            var clie_RTNClienteParameter = clie_RTNCliente != null ?
                new ObjectParameter("clie_RTNCliente", clie_RTNCliente) :
                new ObjectParameter("clie_RTNCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_tbClientes_ValidarRTN", clie_RTNClienteParameter);
        }
    }
}
