//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuarios()
        {
            this.tbUsuarios1 = new HashSet<tbUsuarios>();
            this.tbUsuarios11 = new HashSet<tbUsuarios>();
            this.tbActivos = new HashSet<tbActivos>();
            this.tbActivos1 = new HashSet<tbActivos>();
            this.tbVidaUtil = new HashSet<tbVidaUtil>();
        }
    
        public int usua_Id { get; set; }
        public string usua_UsuarioNombre { get; set; }
        public string usua_UsuarioApellido { get; set; }
        public string usua_Usuario { get; set; }
        public string usua_Contra { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public System.DateTime usua_FechaCreacion { get; set; }
        public Nullable<int> usua_Modificacion { get; set; }
        public Nullable<System.DateTime> usua_FechaModificacion { get; set; }
        public Nullable<bool> usua_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios1 { get; set; }
        public virtual tbUsuarios tbUsuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios11 { get; set; }
        public virtual tbUsuarios tbUsuarios3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActivos> tbActivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActivos> tbActivos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVidaUtil> tbVidaUtil { get; set; }
    }
}
